source 'https://github.com/CocoaPods/Specs.git'

target 'FoundationPlus', :exclusive => true do
  pod "FoundationPlus", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "FoundationPlus", :path => "../"

  pod 'Kiwi'
end
